### ISSUE TITLE
Older Android version support is broken

### ISSUE THREAD

**Issue by ntoskrnl** [bkiers/Liqp#224]
Since 0.8.0 it doesn't work on older versions of Android. 
ThreadLocal.withInitial() is only available on Android 8.0. 

Many `java.time.*` APIs are not available without [desugaring](https://developer.android.com/studio/write/java8-support-table).

```text
ava.util.ServiceConfigurationError: liqp.spi.TypesSupport: Provider liqp.spi.Java7DateTypesSupport could not be instantiated: java.lang.NoSuchMethodError: No static method withInitial(Ljava/util/function/Supplier;)Ljava/lang/ThreadLocal; in class Ljava/lang/ThreadLocal; or its super classes (declaration of 'java.lang.ThreadLocal' appears in /system/framework/core-oj.jar)
        at java.util.ServiceLoader.fail(ServiceLoader.java:225)
        at java.util.ServiceLoader.-wrap1(ServiceLoader.java)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:380)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:448)
        at liqp.spi.SPIHelper.copyIterator(SPIHelper.java:42)
        at liqp.spi.SPIHelper.findProviders(SPIHelper.java:34)
        at liqp.spi.SPIHelper.applyCustomDateTypes(SPIHelper.java:23)
        at liqp.Template.<clinit>(Template.java:39)
        at liqp.Template.parse(Template.java:234)
```

Maybe we can make Date type support an opt-in feature? Or lazy load the modules only when Date / Temporal types are used in the teplate?

**Comment by msangel** [comment]
Java 8 classes are in use is in the logic of date/time manipulation, so not sure if it's possible to make them optional.

It is easy to replace `ThreadLocal.withInitial` with older-compatible code. Will introduce such change in few days.

**Comment by ntoskrnl** [comment]
Maybe wrap instantiation of type-support services into try-catch?

**Comment by msangel** [comment]
@ntoskrnl  мне баг закрывать?
