### ISSUE TITLE
Template parsing context?

### ISSUE THREAD

**Issue by kidpollo** [bkiers/Liqp#26]
I am checking out this library trying to call it directly from clojure. I noticed a that there is scope leaked into the parsing of a template for example parsing a template with a java keyword will result in something like:

```
(liqp.Template/parse "%{{case}}")
NoViableAltException   liqp.parser.LiquidParser.term (LiquidParser.java:5469)
java.lang.RuntimeException: NoViableAltException(21@[])
    at liqp.parser.LiquidParser.reportError(LiquidParser.java:163)
    at liqp.parser.LiquidParser.term(LiquidParser.java:5688)
    at liqp.parser.LiquidParser.rel_expr(LiquidParser.java:5307)
    at liqp.parser.LiquidParser.eq_expr(LiquidParser.java:5211)
    at liqp.parser.LiquidParser.contains_expr(LiquidParser.java:5128)
    at liqp.parser.LiquidParser.and_expr(LiquidParser.java:5039)
    at liqp.parser.LiquidParser.or_expr(LiquidParser.java:4950)
    at liqp.parser.LiquidParser.expr(LiquidParser.java:4894)
    at liqp.parser.LiquidParser.output(LiquidParser.java:4400)
    at liqp.parser.LiquidParser.atom(LiquidParser.java:445)
    at liqp.parser.LiquidParser.block(LiquidParser.java:288)
    at liqp.parser.LiquidParser.parse(LiquidParser.java:194)
    at liqp.Template.<init>(Template.java:65)
    at liqp.Template.parse(Template.java:111)
    at user$eval12727.invokeStatic(form-init1027659148715222265.clj:1)
    at user$eval12727.invoke(form-init1027659148715222265.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6927)
    at clojure.lang.Compiler.eval(Compiler.java:6890)
    at clojure.core$eval.invokeStatic(core.clj:3105)
    at clojure.core$eval.invoke(core.clj:3101)
    at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
    at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
    at clojure.main$repl$fn__7417.invoke(main.clj:258)
    at clojure.main$repl.invokeStatic(main.clj:258)
    at clojure.main$repl.doInvoke(main.clj:174)
    at clojure.lang.RestFn.invoke(RestFn.java:1523)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__12023.invoke(interruptible_eval.clj:87)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invokeStatic(core.clj:646)
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
    at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
    at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__12068$fn__12071.invoke(interruptible_eval.clj:222)
    at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__12063.invoke(interruptible_eval.clj:190)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: NoViableAltException(21@[])
    at liqp.parser.LiquidParser.term(LiquidParser.java:5469)
    ... 39 more
```

I cant really trace this because the parser code seems to be generated so I was wondering if you had any idea what is going on. I cannot think that this would be safe to use without a way to it exploding on templates with legit var names like `case`

**Comment by bkiers** [comment]
Could you post the Liquid template that caused this `NoViableAltException`?

**Comment by kidpollo** [comment]
It's right there first line. It's  something like '{{case}}' or '{{case.id}}' I realize now that case is a liquid thing not necessarily a java or clojure keyword. I think the parser does not like ppl using those words

**Comment by bkiers** [comment]
Yes, `case` is a liquid keyword/tag. Does your input get properly parsed and/or interpreted by the [official Ruby implementation](https://github.com/Shopify/liquid)?

**Comment by kidpollo** [comment]
Yes it does. I'm trying to replace ~8 year old ruby code :P. 'Case' is a
liquid drop in our system for the case model. Very important that it works
:P

**Comment by bkiers** [comment]
Looking at the grammar, I see that `case` should work if its a hash:

```
index
 : Dot id2      -> ^(HASH id2)
 | OBr expr CBr -> ^(INDEX expr)
 ;
```

since `"case"` is matched by the `id2` production.

But `"case"` is not matched by the `id` production:

```
id
 : Id
 | Continue -> Id[$Continue.text]
 ;
```

I think that if you include `CaseStart` in `id`, it should parse ok:

```
id
 : Id
 | Continue -> Id[$Continue.text]
 | CaseStart -> Id[$CaseStart.text]
 ;
```

**Comment by bkiers** [comment]
I'm in UTC+2, so I'll check back tomorrow.
