### ISSUE TITLE
Assign tag only allows one filter

### ISSUE THREAD

**Issue by mbaumbach** [bkiers/Liqp#84]
The following code throws an exception parsing the template:

`Template template = Template.parse("{% assign v = 1 | minus: 1 | plus: 1 %}");`

The exception is:

```
MismatchedTokenException(85!=95)
        at liqp.parser.LiquidParser.reportError(LiquidParser.java:182)
        at liqp.parser.LiquidParser.assignment(LiquidParser.java:5187)
        at liqp.parser.LiquidParser.atom(LiquidParser.java:478)
        at liqp.parser.LiquidParser.block(LiquidParser.java:307)
        at liqp.parser.LiquidParser.parse(LiquidParser.java:213)
        at liqp.Template.<init>(Template.java:78)
        at liqp.Template.parse(Template.java:127)
Caused by: MismatchedTokenException(85!=95)
        at org.antlr.runtime.BaseRecognizer.recoverFromMismatchedToken(BaseRecognizer.java:617)
        at org.antlr.runtime.BaseRecognizer.match(BaseRecognizer.java:115)
        at liqp.parser.LiquidParser.assignment(LiquidParser.java:5139)
```
This template does parse with the Ruby version of Liquid.

A simple workaround is to use multiple assign statements for every filter you want to apply.

I'm not super familiar with ANTLR, but I assume the following assignment definition would fix the problem:

```
assignment
 : tagStart Assign Id EqSign expr filter? TagEnd
 ;
```

```
assignment
 : tagStart Assign Id EqSign expr filter* TagEnd
 ;
```

Thanks for the great library, the ANTLRv4 version is a great improvement too!

**Comment by bkiers** [comment]
Thanks for reporting @mbaumbach, I'll have a look at it.
